name = "as-automotive"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
main = ".output/server/index.mjs"

[vars]
SITE_URL = "https://asautomotive.app"

[env.production]
vars = { SITE_URL = "https://asautomotive.app" }

[env.preview]
vars = { SITE_URL = "https://as-automotive.pages.dev" }
